# Generated by Django 2.2 on 2022-11-19 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dosen',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
